import * as React from 'react'
import {
  AlertCircle,
  Image as ImageIcon,
  Loader2,
  Lock,
  Sparkles,
} from 'lucide-react'

import SiteFooter from '@/components/SiteFooter'
import { BeforeAfterSlider } from '@/components/domain/BeforeAfterSlider'
import { Button } from '@/components/ui/button'
import { Card, CardContent } from '@/components/ui/card'
import { humanRestoreAiHdPrice, humanRestorePrice } from '@/lib/localRepair'
import {
  humanRestorePolicyLinkText,
  humanRestorePolicySummary,
} from '@/contentPolicy'
import trackProductEvent from '@/analytics'

export interface AiHdPreviewPageProps {
  /**
   * Triggers PayPal for the existing preview order. The component
   * never creates a new order — it just hands the orderId/checkoutRef
   * generated by /api/ai-hd-preview back to the same launcher used
   * by the human-tier checkout form.
   */
  onUnlockHd: (payload: {
    checkoutRef: string
    orderId: string
  }) => Promise<{ ok: boolean; error?: string }>
  /**
   * Locked false until PayPal is configured and ready.
   * If false, the unlock button explains why instead of silently
   * failing on click.
   */
  isCheckoutReady: boolean
  /**
   * Launches the Human Retouch checkout (our margin product). Used
   * by the upsell card shown after an AI preview is ready, so buyers
   * who care about face accuracy can switch tiers without leaving
   * the page.
   */
  onUpgradeToHuman: () => void
}

type PreviewState =
  | { kind: 'idle' }
  | { kind: 'submitting' }
  | {
      kind: 'processing'
      orderId: string
      checkoutRef: string
      remaining: number | null
      startedAt: number
    }
  | { kind: 'rate_limited'; retryAfterSeconds: number; message: string }
  | { kind: 'error'; message: string }
  | {
      kind: 'ready'
      orderId: string
      checkoutRef: string
      previewUrl: string
      originalUrl: string
      remaining: number | null
    }

const maxUploadBytes = 15 * 1024 * 1024
const maxDirectPreviewUploadBytes = Math.floor(3.2 * 1024 * 1024)
const maxPreviewEdge = 2400
const allowedMimeTypes = new Set([
  'image/jpeg',
  'image/png',
  'image/webp',
  'image/heic',
  'image/heif',
])
const previewPollIntervalMs = 3000
const previewProcessingTimeoutMs = 2 * 60 * 1000
const previewSessionStorageKey = 'memoryfix_ai_hd_preview_session'

function getProgressStageLabel(progress: number): string {
  if (progress < 15) return 'Analyzing your photo\u2026'
  if (progress < 40) return 'Restoring details\u2026'
  if (progress < 70) return 'Enhancing faces\u2026'
  return 'Applying final polish\u2026'
}

function getProgressStageShort(progress: number): string {
  if (progress < 15) return 'Analyzing\u2026'
  if (progress < 40) return 'Restoring\u2026'
  if (progress < 70) return 'Enhancing\u2026'
  return 'Polish\u2026'
}

function formatBytes(size: number) {
  if (size >= 1024 * 1024) {
    return `${(size / (1024 * 1024)).toFixed(1)} MB`
  }
  return `${Math.max(1, Math.round(size / 1024))} KB`
}

async function readApiResponse(response: Response) {
  const responseText = await response.text()

  if (!responseText) {
    return {}
  }

  try {
    return JSON.parse(responseText)
  } catch {
    return {
      error: response.ok
        ? 'The preview server returned an unreadable response. Please retry in a few seconds.'
        : responseText
            .replace(/<[^>]+>/g, ' ')
            .replace(/\s+/g, ' ')
            .trim()
            .slice(0, 180) ||
          `The preview request failed with status ${response.status}.`,
    }
  }
}

async function preparePreviewImage(file: File): Promise<File> {
  if (file.size <= maxDirectPreviewUploadBytes) {
    return file
  }

  const imageBitmap = await createImageBitmap(file)
  const scale = Math.min(
    1,
    maxPreviewEdge / Math.max(imageBitmap.width, imageBitmap.height)
  )
  const width = Math.max(1, Math.round(imageBitmap.width * scale))
  const height = Math.max(1, Math.round(imageBitmap.height * scale))
  const canvas = document.createElement('canvas')

  canvas.width = width
  canvas.height = height
  canvas.getContext('2d')?.drawImage(imageBitmap, 0, 0, width, height)
  imageBitmap.close()

  const baseName = file.name.replace(/\.[^.]+$/, '') || 'ai-preview'
  const qualities = [0.9, 0.82, 0.74, 0.66, 0.58]

  for (const quality of qualities) {
    const blob = await new Promise<Blob | null>(resolve => {
      canvas.toBlob(resolve, 'image/jpeg', quality)
    })

    if (blob && blob.size <= maxDirectPreviewUploadBytes) {
      return new File([blob], `${baseName}-preview.jpg`, {
        lastModified: Date.now(),
        type: 'image/jpeg',
      })
    }
  }

  throw new Error(
    'This photo is too large for the current preview upload path. Please export it as JPG with the long edge under 2400px and try again.'
  )
}

function savePreviewSession(payload: {
  checkoutRef: string
  orderId: string
  remaining: number | null
  startedAt: number
}) {
  if (typeof window === 'undefined') {
    return
  }

  window.sessionStorage.setItem(
    previewSessionStorageKey,
    JSON.stringify(payload)
  )
}

function readPreviewSession(): {
  checkoutRef: string
  orderId: string
  remaining: number | null
  startedAt: number
} | null {
  if (typeof window === 'undefined') {
    return null
  }

  const raw = window.sessionStorage.getItem(previewSessionStorageKey)

  if (!raw) {
    return null
  }

  try {
    const parsed = JSON.parse(raw)

    if (!parsed?.checkoutRef || !parsed?.orderId) {
      return null
    }

    return {
      checkoutRef: String(parsed.checkoutRef),
      orderId: String(parsed.orderId),
      remaining: typeof parsed.remaining === 'number' ? parsed.remaining : null,
      startedAt:
        typeof parsed.startedAt === 'number' ? parsed.startedAt : Date.now(),
    }
  } catch {
    return null
  }
}

function clearPreviewSession() {
  if (typeof window === 'undefined') {
    return
  }

  window.sessionStorage.removeItem(previewSessionStorageKey)
}

export function AiHdPreviewPage({
  isCheckoutReady,
  onUnlockHd,
  onUpgradeToHuman,
}: AiHdPreviewPageProps) {
  const fileInputRef = React.useRef<HTMLInputElement>(null)
  const [selectedFile, setSelectedFile] = React.useState<File | null>(null)
  const [policyAccepted, setPolicyAccepted] = React.useState(false)
  const [state, setState] = React.useState<PreviewState>({ kind: 'idle' })
  const [isUnlocking, setIsUnlocking] = React.useState(false)
  const [unlockError, setUnlockError] = React.useState('')
  const processingState = state.kind === 'processing' ? state : null
  const [thumbnailUrl, setThumbnailUrl] = React.useState<string | null>(null)
  const [simulatedProgress, setSimulatedProgress] = React.useState(0)
  const submittingStartRef = React.useRef<number>(0)

  React.useEffect(() => {
    if (!selectedFile) {
      setThumbnailUrl(null)
      return
    }
    const url = URL.createObjectURL(selectedFile)
    setThumbnailUrl(url)
    return () => URL.revokeObjectURL(url)
  }, [selectedFile])

  const isProgressActive =
    state.kind === 'submitting' || state.kind === 'processing'

  React.useEffect(() => {
    if (!isProgressActive) {
      setSimulatedProgress(0)
      return undefined
    }

    const startedAt =
      processingState?.startedAt || submittingStartRef.current || Date.now()
    const expectedMs = 45000

    const interval = setInterval(() => {
      const elapsed = Date.now() - startedAt
      const t = Math.min(elapsed / expectedMs, 1)
      const eased = 1 - (1 - t) * (1 - t)
      setSimulatedProgress(Math.min(90, Math.round(eased * 90)))
    }, 300)

    return () => clearInterval(interval)
  }, [isProgressActive, processingState])

  React.useEffect(() => {
    const savedSession = readPreviewSession()

    if (!savedSession) {
      return
    }

    setState(currentState => {
      if (currentState.kind !== 'idle') {
        return currentState
      }

      return {
        kind: 'processing',
        checkoutRef: savedSession.checkoutRef,
        orderId: savedSession.orderId,
        remaining: savedSession.remaining,
        startedAt: savedSession.startedAt,
      }
    })
  }, [])

  React.useEffect(() => {
    if (!processingState) {
      return undefined
    }

    const currentProcessingState = processingState
    savePreviewSession(currentProcessingState)

    let active = true
    let timer: ReturnType<typeof setTimeout> | null = null

    async function pollPreview() {
      if (!active) {
        return
      }

      if (
        Date.now() - currentProcessingState.startedAt >
        previewProcessingTimeoutMs
      ) {
        clearPreviewSession()
        setState({
          kind: 'error',
          message:
            'The AI preview is taking longer than expected. Please refresh and try again, or contact us if this keeps happening.',
        })
        return
      }

      try {
        const params = new URLSearchParams({
          checkoutRef: currentProcessingState.checkoutRef,
          orderId: currentProcessingState.orderId,
        })
        const response = await fetch(
          `/api/human-restore-order?${params.toString()}`
        )
        const responseBody = await response.json().catch(() => null)

        if (!active) {
          return
        }

        if (!response.ok || !responseBody?.ok || !responseBody?.order) {
          setState({
            kind: 'error',
            message:
              responseBody?.error ||
              'The AI HD preview status could not be checked. Please retry in a few seconds.',
          })
          return
        }

        const { order } = responseBody

        if (
          order.previewStatus === 'ready' &&
          order.previewUrl &&
          order.originalUrl
        ) {
          clearPreviewSession()
          trackProductEvent('ai_hd_preview_ready', {
            order_id_created: Boolean(order.orderId),
            source: 'order_poll',
          })
          setState({
            kind: 'ready',
            checkoutRef: currentProcessingState.checkoutRef,
            orderId: currentProcessingState.orderId,
            originalUrl: order.originalUrl,
            previewUrl: order.previewUrl,
            remaining: currentProcessingState.remaining,
          })
          return
        }

        if (order.previewStatus === 'failed') {
          clearPreviewSession()
          setState({
            kind: 'error',
            message:
              order.previewError ||
              'The AI HD preview could not be generated for this photo.',
          })
          return
        }

        timer = window.setTimeout(pollPreview, previewPollIntervalMs)
      } catch (error) {
        if (!active) {
          return
        }

        setState({
          kind: 'error',
          message:
            error instanceof Error
              ? error.message
              : 'The AI HD preview request failed. Please try again.',
        })
      }
    }

    timer = window.setTimeout(pollPreview, 1200)

    return () => {
      active = false
      if (timer) {
        window.clearTimeout(timer)
      }
    }
  }, [processingState])

  function pickFile() {
    fileInputRef.current?.click()
  }

  function onFileChange(event: React.ChangeEvent<HTMLInputElement>) {
    const file = event.target.files?.[0]
    if (!file) return

    clearPreviewSession()

    if (!allowedMimeTypes.has(file.type)) {
      setState({
        kind: 'error',
        message: 'Please choose a JPG, PNG, WebP, HEIC, or HEIF image.',
      })
      return
    }

    if (file.size > maxUploadBytes) {
      setState({
        kind: 'error',
        message: 'Please keep the photo under 15 MB for the preview.',
      })
      return
    }

    setSelectedFile(file)
    setState({ kind: 'idle' })

    if (fileInputRef.current) {
      fileInputRef.current.value = ''
    }
  }

  async function generatePreview() {
    if (!selectedFile) {
      setState({
        kind: 'error',
        message: 'Drop a photo first so the AI has something to restore.',
      })
      return
    }

    if (!policyAccepted) {
      setState({
        kind: 'error',
        message:
          'Please confirm the photo follows our Acceptable Use Policy before generating a preview.',
      })
      return
    }

    submittingStartRef.current = Date.now()
    setState({ kind: 'submitting' })

    try {
      const uploadFile = await preparePreviewImage(selectedFile)
      const formData = new FormData()

      formData.append('photo', uploadFile)
      formData.append('contentPolicyAccepted', 'true')

      trackProductEvent('ai_hd_preview_started', {
        file_size_bucket:
          selectedFile.size > 5 * 1024 * 1024 ? 'large' : 'small',
        upload_compressed: uploadFile !== selectedFile,
      })

      const response = await fetch('/api/ai-hd-preview', {
        body: formData,
        method: 'POST',
      })
      const responseBody = await readApiResponse(response)

      if (response.status === 429) {
        setState({
          kind: 'rate_limited',
          retryAfterSeconds: responseBody?.retryAfterSeconds || 0,
          message:
            responseBody?.error ||
            'You used your free AI HD previews for today. Please try again tomorrow.',
        })
        return
      }

      if (
        response.ok &&
        responseBody?.ok &&
        responseBody?.previewStatus === 'processing'
      ) {
        const startedAt = Date.now()
        savePreviewSession({
          checkoutRef: responseBody.checkoutRef || '',
          orderId: responseBody.orderId,
          remaining:
            typeof responseBody.remaining === 'number'
              ? responseBody.remaining
              : null,
          startedAt,
        })
        setState({
          kind: 'processing',
          checkoutRef: responseBody.checkoutRef || '',
          orderId: responseBody.orderId,
          remaining:
            typeof responseBody.remaining === 'number'
              ? responseBody.remaining
              : null,
          startedAt,
        })
        return
      }

      if (!response.ok || !responseBody?.ok) {
        setState({
          kind: 'error',
          message:
            responseBody?.error ||
            'The AI HD preview could not be generated right now. Please retry in a few seconds.',
        })
        return
      }

      trackProductEvent('ai_hd_preview_ready', {
        order_id_created: Boolean(responseBody.orderId),
      })

      setState({
        kind: 'ready',
        checkoutRef: responseBody.checkoutRef || '',
        orderId: responseBody.orderId,
        originalUrl: responseBody.originalUrl,
        previewUrl: responseBody.previewUrl,
        remaining:
          typeof responseBody.remaining === 'number'
            ? responseBody.remaining
            : null,
      })
    } catch (error) {
      setState({
        kind: 'error',
        message:
          error instanceof Error
            ? error.message
            : 'The AI HD preview request failed. Please try again.',
      })
    }
  }

  async function handleUnlock() {
    if (state.kind !== 'ready') return

    if (!isCheckoutReady) {
      setUnlockError(
        'Secure checkout is still loading. Please retry in a second.'
      )
      return
    }

    const { orderId, checkoutRef } = state
    setIsUnlocking(true)
    setUnlockError('')

    trackProductEvent('ai_hd_unlock_clicked', { has_preview: true })

    const launchResult = await onUnlockHd({ checkoutRef, orderId })

    setIsUnlocking(false)

    if (!launchResult.ok) {
      setUnlockError(
        launchResult.error ||
          'Secure checkout could not open. Please retry in a moment.'
      )
    }
  }

  function resetForNewPreview() {
    setSelectedFile(null)
    setPolicyAccepted(false)
    setState({ kind: 'idle' })
    setUnlockError('')
    setIsUnlocking(false)
    clearPreviewSession()
  }

  const isWorking =
    state.kind === 'submitting' || state.kind === 'processing' || isUnlocking
  const isReady = state.kind === 'ready'

  return (
    <div className="bg-background">
      <section className="container py-16 md:py-20">
        <div className="mx-auto max-w-3xl text-center">
          <p className="mb-3 font-mono text-xs uppercase tracking-[0.2em] text-muted-foreground">
            AI HD Restore · {humanRestoreAiHdPrice}
          </p>
          <h1 className="font-serif text-3xl font-semibold leading-tight tracking-tight text-foreground md:text-5xl">
            See the AI restoration first. Pay only if you love it.
          </h1>
          <p className="mt-4 text-base leading-relaxed text-muted-foreground md:text-lg">
            Drop your old photo below. We&apos;ll generate a watermarked preview
            in about a minute. Unlock the full-resolution download for{' '}
            {humanRestoreAiHdPrice} when you&apos;re happy.
          </p>
        </div>

        <div className="mx-auto mt-10 grid max-w-5xl gap-6 lg:grid-cols-[1.05fr_0.95fr]">
          <Card className="border border-primary/20 shadow-card">
            <CardContent className="flex flex-col gap-5 p-6 md:p-8">
              <div className="flex items-center gap-2">
                <span className="flex h-8 w-8 items-center justify-center rounded-full bg-primary/15 text-primary">
                  <ImageIcon className="h-4 w-4" aria-hidden />
                </span>
                <h2 className="font-serif text-xl font-semibold text-foreground">
                  1. Upload your photo
                </h2>
              </div>

              <button
                type="button"
                onClick={pickFile}
                disabled={isWorking}
                className="flex flex-col items-center justify-center gap-2 rounded-lg border-2 border-dashed border-primary/30 bg-secondary/40 px-6 py-10 text-center transition hover:border-primary/60 hover:bg-secondary disabled:cursor-not-allowed disabled:opacity-60"
              >
                <span className="font-serif text-lg font-medium text-foreground">
                  {selectedFile ? selectedFile.name : 'Click to choose a photo'}
                </span>
                <span className="text-xs text-muted-foreground">
                  {selectedFile
                    ? `${formatBytes(selectedFile.size)} · ${
                        selectedFile.type || 'image'
                      }`
                    : 'JPG, PNG, WebP, HEIC, HEIF · up to 15 MB'}
                </span>
              </button>

              <input
                ref={fileInputRef}
                type="file"
                accept="image/*"
                className="sr-only"
                onChange={onFileChange}
              />

              <label
                htmlFor="ai-hd-policy"
                className="flex cursor-pointer items-start gap-3 rounded-md border border-border bg-background p-3 text-sm leading-relaxed text-muted-foreground"
              >
                <input
                  id="ai-hd-policy"
                  type="checkbox"
                  checked={policyAccepted}
                  onChange={event => setPolicyAccepted(event.target.checked)}
                  className="mt-1"
                  disabled={isWorking}
                />
                <span>
                  {humanRestorePolicySummary}{' '}
                  <a
                    href="/acceptable-use"
                    className="font-medium text-foreground underline-offset-4 hover:underline"
                    target="_blank"
                    rel="noreferrer"
                  >
                    {humanRestorePolicyLinkText}
                  </a>
                </span>
              </label>

              <Button
                variant="accent"
                size="lg"
                onClick={generatePreview}
                disabled={isWorking}
                className="w-full"
              >
                {state.kind === 'submitting' || state.kind === 'processing' ? (
                  <span className="inline-flex items-center gap-2">
                    <div className="h-1.5 w-12 overflow-hidden rounded-full bg-primary/15">
                      <div
                        className="h-full rounded-full bg-primary transition-all duration-500 ease-out"
                        style={{ width: `${simulatedProgress}%` }}
                      />
                    </div>
                    {state.kind === 'processing'
                      ? `${getProgressStageShort(
                          simulatedProgress
                        )} ${simulatedProgress}%`
                      : 'Generating preview\u2026'}
                  </span>
                ) : (
                  'Generate AI preview (free)'
                )}
              </Button>

              <p className="text-xs leading-relaxed text-muted-foreground">
                Your photo is processed on private Supabase storage and is never
                used to train models. Free previews are limited to 3 per day per
                IP.
              </p>

              {state.kind === 'rate_limited' && (
                <div className="flex items-start gap-2 rounded-md border border-destructive/40 bg-destructive/10 p-3 text-sm text-destructive">
                  <AlertCircle
                    className="mt-0.5 h-4 w-4 shrink-0"
                    aria-hidden
                  />
                  <span>{state.message}</span>
                </div>
              )}

              {state.kind === 'error' && (
                <div className="flex items-start gap-2 rounded-md border border-destructive/40 bg-destructive/10 p-3 text-sm text-destructive">
                  <AlertCircle
                    className="mt-0.5 h-4 w-4 shrink-0"
                    aria-hidden
                  />
                  <span>{state.message}</span>
                </div>
              )}
            </CardContent>
          </Card>

          <Card className="border border-primary/20 shadow-card">
            <CardContent className="flex h-full flex-col gap-5 p-6 md:p-8">
              <div className="flex items-center gap-2">
                <span className="flex h-8 w-8 items-center justify-center rounded-full bg-primary/15 text-primary">
                  <Lock className="h-4 w-4" aria-hidden />
                </span>
                <h2 className="font-serif text-xl font-semibold text-foreground">
                  2. Unlock the HD download
                </h2>
              </div>

              {!isReady &&
                state.kind !== 'processing' &&
                state.kind !== 'submitting' && (
                  <div className="flex flex-1 flex-col items-center justify-center gap-3 rounded-lg border border-dashed border-primary/20 bg-secondary/40 p-8 text-center">
                    <p className="font-serif text-base text-foreground">
                      Your watermarked preview will appear here.
                    </p>
                    <p className="text-sm text-muted-foreground">
                      Generation usually takes 20–60 seconds depending on the AI
                      provider load.
                    </p>
                  </div>
                )}

              {(state.kind === 'processing' || state.kind === 'submitting') && (
                <div className="relative flex flex-1 flex-col items-center justify-center overflow-hidden rounded-lg border border-dashed border-primary/20 bg-secondary/40">
                  {thumbnailUrl && (
                    <img
                      src={thumbnailUrl}
                      alt=""
                      aria-hidden
                      className="absolute inset-0 h-full w-full object-cover opacity-25 blur-lg"
                    />
                  )}
                  <div className="relative z-10 flex w-full flex-col items-center gap-4 p-8 text-center">
                    <div className="h-1.5 w-48 overflow-hidden rounded-full bg-primary/15">
                      <div
                        className="h-full rounded-full bg-primary transition-all duration-500 ease-out"
                        style={{ width: `${simulatedProgress}%` }}
                      />
                    </div>
                    <p className="font-serif text-base text-foreground">
                      {getProgressStageLabel(simulatedProgress)}
                    </p>
                    <p className="text-sm text-muted-foreground">
                      {simulatedProgress}% complete &mdash; please keep this tab
                      open.
                    </p>
                  </div>
                </div>
              )}

              {isReady && (
                <>
                  <BeforeAfterSlider
                    afterAlt="AI HD watermarked preview"
                    afterLabel="AI Preview"
                    afterSrc={state.previewUrl}
                    beforeAlt="Original photo"
                    beforeLabel="Original"
                    beforeSrc={state.originalUrl}
                    className="aspect-[4/3]"
                    initialPosition={50}
                  />
                  <p className="text-xs leading-relaxed text-muted-foreground">
                    The HD download you receive after payment has{' '}
                    <strong className="text-foreground">no watermark</strong>{' '}
                    and is at the AI&apos;s full output resolution.
                  </p>

                  <Button
                    variant="accent"
                    size="lg"
                    onClick={handleUnlock}
                    disabled={!isCheckoutReady || isWorking}
                    className="w-full"
                  >
                    {isUnlocking ? (
                      <span className="inline-flex items-center gap-2">
                        <Loader2 className="h-4 w-4 animate-spin" aria-hidden />
                        Opening secure checkout…
                      </span>
                    ) : (
                      <span className="inline-flex items-center gap-2">
                        <Lock className="h-4 w-4" aria-hidden />
                        Unlock HD download — {humanRestoreAiHdPrice}
                      </span>
                    )}
                  </Button>

                  {!isCheckoutReady && (
                    <p className="text-xs text-muted-foreground">
                      Secure checkout is loading. Please wait a moment.
                    </p>
                  )}

                  {unlockError && (
                    <div className="flex items-start gap-2 rounded-md border border-destructive/40 bg-destructive/10 p-3 text-sm text-destructive">
                      <AlertCircle
                        className="mt-0.5 h-4 w-4 shrink-0"
                        aria-hidden
                      />
                      <span>{unlockError}</span>
                    </div>
                  )}

                  <button
                    type="button"
                    onClick={resetForNewPreview}
                    className="text-xs font-medium text-muted-foreground underline-offset-4 hover:underline"
                  >
                    Try a different photo
                  </button>

                  {typeof state.remaining === 'number' && (
                    <p className="text-xs text-muted-foreground">
                      Free previews remaining today:{' '}
                      <strong className="text-foreground">
                        {state.remaining}
                      </strong>
                    </p>
                  )}
                </>
              )}
            </CardContent>
          </Card>
        </div>

        {isReady && (
          <Card className="mx-auto mt-10 max-w-3xl border-primary/40 bg-gradient-to-br from-primary/5 via-background to-background shadow-float">
            <CardContent className="flex flex-col items-start gap-4 p-6 md:flex-row md:items-center md:gap-6 md:p-8">
              <span className="flex h-12 w-12 shrink-0 items-center justify-center rounded-full bg-primary/15 text-primary">
                <Sparkles className="h-6 w-6" aria-hidden />
              </span>
              <div className="flex-1">
                <p className="font-mono text-xs uppercase tracking-[0.2em] text-primary">
                  Faces must stay faithful?
                </p>
                <h3 className="mt-2 font-serif text-xl font-semibold leading-tight text-foreground md:text-2xl">
                  Have a real retoucher finish this photo by hand.
                </h3>
                <p className="mt-2 text-sm leading-relaxed text-muted-foreground">
                  AI may shift facial features slightly. For wedding, funeral or
                  heirloom portraits, a professional retoucher preserves every
                  feature — delivered within 24 hours, one free revision
                  included.
                </p>
              </div>
              <Button
                variant="accent"
                size="lg"
                onClick={() => {
                  trackProductEvent('click_human_restore', {
                    destination: 'ai_hd_preview_upsell',
                    tier: 'human',
                  })
                  onUpgradeToHuman()
                }}
                disabled={!isCheckoutReady}
                className="w-full shrink-0 md:w-auto"
              >
                Upgrade — {humanRestorePrice}
              </Button>
            </CardContent>
          </Card>
        )}

        {!isReady && (
          <p className="mx-auto mt-12 max-w-2xl text-center text-sm leading-relaxed text-muted-foreground">
            Want a face-accurate, human-retouched version instead?{' '}
            <button
              type="button"
              onClick={onUpgradeToHuman}
              className="font-semibold text-foreground underline-offset-4 hover:underline"
            >
              See the {humanRestorePrice} Human Retouch tier →
            </button>
          </p>
        )}
      </section>

      <SiteFooter />
    </div>
  )
}

export default AiHdPreviewPage
